DELETE FROM characters
WHERE name IN (
    'Cleopatra',
    'Julio César',
    'Confucio',
    'Aristóteles',
    'Alejandro Magno',
    'Ashoka',
    'Hipatia',
    'Mansa Musa',
    'Gengis Kan',
    'Juana de Arco',
    'Leonardo da Vinci',
    'William Shakespeare',
    'Galileo Galilei',
    'Isaac Newton',
    'Sor Juana Inés de la Cruz',
    'Napoleón Bonaparte',
    'Simón Bolívar',
    'Jane Austen',
    'Charles Darwin',
    'Florence Nightingale',
    'Abraham Lincoln',
    'Ada Lovelace',
    'Marie Curie',
    'Nikola Tesla',
    'Albert Einstein',
    'Mahatma Gandhi',
    'Frida Kahlo',
    'Amelia Earhart',
    'Nelson Mandela',
    'Martin Luther King Jr.',
    'Rosa Parks',
    'Alan Turing',
    'Lionel Messi',
    'Diego Maradona',
    'Pelé',
    'Cristiano Ronaldo',
    'Zinedine Zidane'
);