SELECT setval(
    pg_get_serial_sequence('characters', 'id'),
    COALESCE((SELECT MAX(id) FROM characters), 1),
    EXISTS (SELECT 1 FROM characters)
);

INSERT INTO characters (
    name,
    gender,
    period,
    country,
    continent,
    know_for,
    position,
    birth_year,
    year_of_death
) VALUES
    ('Cleopatra', 'Femenino', 'Edad Antigua', 'Egipto', 'Africa', 'Última gobernante del Egipto ptolemaico', 'Reina', -69, -30),
    ('Julio César', 'Masculino', 'Edad Antigua', 'Italia', 'Europa', 'Conquista de la Galia y reformas romanas', 'Político y militar romano', -100, -44),
    ('Confucio', 'Masculino', 'Edad Antigua', 'China', 'Asia', 'Enseñanzas filosóficas y éticas', 'Filósofo', -551, -479),
    ('Aristóteles', 'Masculino', 'Edad Antigua', 'Grecia', 'Europa', 'Aportes a la filosofía y las ciencias', 'Filósofo', -384, -322),
    ('Alejandro Magno', 'Masculino', 'Edad Antigua', 'Macedonia', 'Europa', 'Conquista de un vasto imperio', 'Rey y militar', -356, -323),
    ('Ashoka', 'Masculino', 'Edad Antigua', 'India', 'Asia', 'Gobierno del Imperio Maurya', 'Emperador', -304, -232),
    ('Hipatia', 'Femenino', 'Edad Antigua', 'Egipto', 'Africa', 'Enseñanza de filosofía y matemática', 'Filósofa y matemática', 350, 415),
    ('Mansa Musa', 'Masculino', 'Edad Media', 'Mali', 'Africa', 'Gobierno del Imperio de Mali', 'Emperador', 1280, 1337),
    ('Gengis Kan', 'Masculino', 'Edad Media', 'Mongolia', 'Asia', 'Fundación del Imperio mongol', 'Gobernante y militar', 1162, 1227),
    ('Juana de Arco', 'Femenino', 'Edad Media', 'Francia', 'Europa', 'Participación en la Guerra de los Cien Años', 'Militar', 1412, 1431),
    ('Leonardo da Vinci', 'Masculino', 'Edad Moderna', 'Italia', 'Europa', 'Obras artísticas e inventos', 'Artista e inventor', 1452, 1519),
    ('William Shakespeare', 'Masculino', 'Edad Moderna', 'Inglaterra', 'Europa', 'Obras teatrales y poesía', 'Escritor', 1564, 1616),
    ('Galileo Galilei', 'Masculino', 'Edad Moderna', 'Italia', 'Europa', 'Aportes a la astronomía y la física', 'Científico', 1564, 1642),
    ('Isaac Newton', 'Masculino', 'Edad Moderna', 'Inglaterra', 'Europa', 'Leyes del movimiento y gravitación', 'Físico y matemático', 1643, 1727),
    ('Sor Juana Inés de la Cruz', 'Femenino', 'Edad Moderna', 'México', 'America', 'Poesía y defensa del acceso de las mujeres al conocimiento', 'Escritora', 1648, 1695),
    ('Napoleón Bonaparte', 'Masculino', 'Edad Contemporanea', 'Francia', 'Europa', 'Guerras napoleónicas y reformas legales', 'Emperador y militar', 1769, 1821),
    ('Simón Bolívar', 'Masculino', 'Edad Contemporanea', 'Venezuela', 'America', 'Independencia de países sudamericanos', 'Militar y político', 1783, 1830),
    ('Jane Austen', 'Femenino', 'Edad Contemporanea', 'Inglaterra', 'Europa', 'Novelas sobre la sociedad de su época', 'Escritora', 1775, 1817),
    ('Charles Darwin', 'Masculino', 'Edad Contemporanea', 'Inglaterra', 'Europa', 'Teoría de la evolución por selección natural', 'Naturalista', 1809, 1882),
    ('Florence Nightingale', 'Femenino', 'Edad Contemporanea', 'Inglaterra', 'Europa', 'Reformas de enfermería y salud pública', 'Enfermera', 1820, 1910),
    ('Abraham Lincoln', 'Masculino', 'Edad Contemporanea', 'Estados Unidos', 'America', 'Abolición de la esclavitud en Estados Unidos', 'Presidente y abogado', 1809, 1865),
    ('Ada Lovelace', 'Femenino', 'Edad Contemporanea', 'Inglaterra', 'Europa', 'Primer algoritmo pensado para una máquina', 'Matemática', 1815, 1852),
    ('Marie Curie', 'Femenino', 'Edad Contemporanea', 'Polonia', 'Europa', 'Investigaciones sobre la radiactividad', 'Física y química', 1867, 1934),
    ('Nikola Tesla', 'Masculino', 'Edad Contemporanea', 'Serbia', 'Europa', 'Desarrollo de sistemas eléctricos de corriente alterna', 'Inventor e ingeniero', 1856, 1943),
    ('Albert Einstein', 'Masculino', 'Edad Contemporanea', 'Alemania', 'Europa', 'Teoría de la relatividad', 'Físico', 1879, 1955),
    ('Mahatma Gandhi', 'Masculino', 'Edad Contemporanea', 'India', 'Asia', 'Resistencia no violenta por la independencia de India', 'Activista y político', 1869, 1948),
    ('Frida Kahlo', 'Femenino', 'Edad Contemporanea', 'México', 'America', 'Pintura autorreferencial', 'Artista', 1907, 1954),
    ('Amelia Earhart', 'Femenino', 'Edad Contemporanea', 'Estados Unidos', 'America', 'Récords y vuelos pioneros de aviación', 'Aviadora', 1897, 1937),
    ('Nelson Mandela', 'Masculino', 'Edad Contemporanea', 'Sudáfrica', 'Africa', 'Lucha contra el apartheid', 'Activista y político', 1918, 2013),
    ('Martin Luther King Jr.', 'Masculino', 'Edad Contemporanea', 'Estados Unidos', 'America', 'Movimiento por los derechos civiles', 'Activista y religioso', 1929, 1968),
    ('Rosa Parks', 'Femenino', 'Edad Contemporanea', 'Estados Unidos', 'America', 'Lucha por los derechos civiles', 'Activista', 1913, 2005),
    ('Alan Turing', 'Masculino', 'Edad Contemporanea', 'Inglaterra', 'Europa', 'Fundamentos de la computación y criptoanálisis', 'Matemático y científico', 1912, 1954),
    ('Lionel Messi', 'Masculino', 'Edad Contemporanea', 'Argentina', 'America', 'Campeón del mundo con Argentina y ganador de múltiples Balones de Oro', 'Delantero', 1987, 0),
    ('Diego Maradona', 'Masculino', 'Edad Contemporanea', 'Argentina', 'America', 'Campeón del mundo con Argentina en 1986', 'Mediocampista ofensivo', 1960, 2020),
    ('Pelé', 'Masculino', 'Edad Contemporanea', 'Brasil', 'America', 'Ganador de tres Copas Mundiales con Brasil', 'Delantero', 1940, 2022),
    ('Cristiano Ronaldo', 'Masculino', 'Edad Contemporanea', 'Portugal', 'Europa', 'Campeón europeo con Portugal y goleador histórico', 'Delantero', 1985, 0),
    ('Zinedine Zidane', 'Masculino', 'Edad Contemporanea', 'Francia', 'Europa', 'Campeón del mundo con Francia en 1998', 'Mediocampista', 1972, 0);

INSERT INTO character_occupations (character_id, occupation_id)
SELECT character.id, occupation.id
FROM (
    VALUES
        ('Cleopatra', 'Gobernante'),
        ('Cleopatra', 'Político'),
        ('Julio César', 'Gobernante'),
        ('Julio César', 'Militar'),
        ('Julio César', 'Político'),
        ('Confucio', 'Filósofo'),
        ('Confucio', 'Escritor'),
        ('Aristóteles', 'Filósofo'),
        ('Aristóteles', 'Científico'),
        ('Alejandro Magno', 'Gobernante'),
        ('Alejandro Magno', 'Militar'),
        ('Ashoka', 'Gobernante'),
        ('Ashoka', 'Militar'),
        ('Hipatia', 'Filósofo'),
        ('Hipatia', 'Matemático'),
        ('Hipatia', 'Científico'),
        ('Mansa Musa', 'Gobernante'),
        ('Gengis Kan', 'Gobernante'),
        ('Gengis Kan', 'Militar'),
        ('Juana de Arco', 'Militar'),
        ('Juana de Arco', 'Religioso'),
        ('Leonardo da Vinci', 'Artista'),
        ('Leonardo da Vinci', 'Inventor'),
        ('William Shakespeare', 'Escritor'),
        ('Galileo Galilei', 'Científico'),
        ('Isaac Newton', 'Científico'),
        ('Isaac Newton', 'Matemático'),
        ('Sor Juana Inés de la Cruz', 'Escritor'),
        ('Sor Juana Inés de la Cruz', 'Religioso'),
        ('Napoleón Bonaparte', 'Gobernante'),
        ('Napoleón Bonaparte', 'Militar'),
        ('Napoleón Bonaparte', 'Político'),
        ('Simón Bolívar', 'Militar'),
        ('Simón Bolívar', 'Político'),
        ('Jane Austen', 'Escritor'),
        ('Charles Darwin', 'Científico'),
        ('Florence Nightingale', 'Enfermería'),
        ('Florence Nightingale', 'Activista'),
        ('Abraham Lincoln', 'Político'),
        ('Abraham Lincoln', 'Abogado'),
        ('Ada Lovelace', 'Matemático'),
        ('Ada Lovelace', 'Escritor'),
        ('Marie Curie', 'Científico'),
        ('Marie Curie', 'Matemático'),
        ('Nikola Tesla', 'Inventor'),
        ('Nikola Tesla', 'Científico'),
        ('Albert Einstein', 'Científico'),
        ('Mahatma Gandhi', 'Activista'),
        ('Mahatma Gandhi', 'Político'),
        ('Frida Kahlo', 'Artista'),
        ('Amelia Earhart', 'Aviador'),
        ('Amelia Earhart', 'Explorador'),
        ('Nelson Mandela', 'Activista'),
        ('Nelson Mandela', 'Político'),
        ('Nelson Mandela', 'Abogado'),
        ('Martin Luther King Jr.', 'Activista'),
        ('Martin Luther King Jr.', 'Religioso'),
        ('Rosa Parks', 'Activista'),
        ('Alan Turing', 'Matemático'),
        ('Alan Turing', 'Científico'),
        ('Lionel Messi', 'Futbolista'),
        ('Diego Maradona', 'Futbolista'),
        ('Pelé', 'Futbolista'),
        ('Cristiano Ronaldo', 'Futbolista'),
        ('Zinedine Zidane', 'Futbolista')
) AS seed(character_name, occupation_name)
JOIN characters character
    ON character.name = seed.character_name
JOIN occupations occupation
    ON occupation.name = seed.occupation_name;